# Generated by Django 3.2.12 on 2022-03-23 16:46

import catalog.validators
import core.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('slug', models.CharField(max_length=200, unique=True, validators=[core.validators.ConsistsValidator({'H', 'M', 'W', 'e', 's', 't', 'J', 'y', 'm', '0', 'l', 'B', 'b', 'f', 'u', 'w', 'C', 'V', 'h', 'k', 'i', 'L', '5', 'D', 'r', '2', 'n', 'j', 'z', 'X', 'P', 'T', 'o', 'Y', 'R', 'a', 'v', 'I', 'A', 'E', 'F', 'Q', 'c', 'G', '4', 'U', 'p', 'N', 'K', 'S', '8', 'Z', '7', 'g', 'x', 'O', '6', '-', '9', 'd', '_', '3', '1', 'q'})])),
                ('weight', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(32767)], verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('slug', models.CharField(max_length=200, unique=True, validators=[core.validators.ConsistsValidator({'H', 'M', 'W', 'e', 's', 't', 'J', 'y', 'm', '0', 'l', 'B', 'b', 'f', 'u', 'w', 'C', 'V', 'h', 'k', 'i', 'L', '5', 'D', 'r', '2', 'n', 'j', 'z', 'X', 'P', 'T', 'o', 'Y', 'R', 'a', 'v', 'I', 'A', 'E', 'F', 'Q', 'c', 'G', '4', 'U', 'p', 'N', 'K', 'S', '8', 'Z', '7', 'g', 'x', 'O', '6', '-', '9', 'd', '_', '3', '1', 'q'})])),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('text', models.TextField(validators=[catalog.validators.MinNumWordsValidator(2), catalog.validators.OccurrenceWordsValidator(('превосходно', 'роскошно'))], verbose_name='Текст')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.category')),
                ('tags', models.ManyToManyField(to='catalog.Tag')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
