# Generated by Django 3.2.12 on 2022-03-24 13:15

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='', help_text='Макс 150 символов', max_length=150, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default='', help_text='Макс 150 символов', max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Максимальная длина - 200 символов, уникальное значение рамках таблицы, только цифры, буквы латиницы и символы - и _', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(help_text='Минимум два слова. Обязательно содержится слово "превосходно" или "роскошно"', validators=[catalog.validators.MinNumWordsValidator(2), catalog.validators.OccurrenceWordsValidator(('превосходно', 'роскошно'))], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Максимальная длина - 200 символов, уникальное значение рамках таблицы, только цифры, буквы латиницы и символы - и _', max_length=200, unique=True),
        ),
    ]
