# Generated by Django 3.2.12 on 2022-04-09 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20220324_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('weight',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('category__weight',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
